### PR TITLE
Added importer for KBaseGenerics.DataMatrix

### PR DESCRIPTION
**Pull request by jmchandonia**

### CODE REVIEW

**Comment by nlharris** [comment]
Are we still using narrative_method_specs_ci?? I didn't think we used that anymore. @msneddon @briehl

**Comment by scanon** [comment]
We use it for types which is used by the uploaders and downloaders. 

I would like to hold off on this until we review the underlying type. 

>

**Comment by rsutormin** [comment]
@scanon: I don't think there is any danger in merging it. In worst case you'll have new non-working item in Import tab. Other items shouldn't be touched by that. On the other hand merging it is the way how you can play with new uploader and figure what's wrong.

**Comment by jmchandonia** [comment]
Updated to work with latest Generics objects (e.g., NDarray rather than DataMatrix).

**Pull request merged**
