### PR TITLE
first version of new GenomeAnnotation and Assembly object type uploads

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by mlhenderson** [comment]
Checks failed, but those are for other specs that are not included in this PR.  We should merge this in.

**Comment by mlhenderson** [comment]
@msneddon can we get this merged in?  Also looks like checks are failing for many other specs.

**Comment by msneddon** [comment]
Yeah- you should all feel free to merge anytime into narrative_method_specs_ci since it is just for testing and completely disconnected from the main narrative_method_specs repo.

**Comment by msneddon** [comment]
And one more quick note- some recent changes to the narrative method store was causing tests to fail on valid specs for a bit, but that has been fixed.  The only method that still seems invalid is: associate_metadata_to_reads: https://travis-ci.org/kbase/narrative_method_specs_ci/builds/89349209#L554 but again it's ok if tests fail in this repo.

**Comment by r2sunita** [comment]
Thanks Mike. It was my mistake, though it was minor. I have fixed it. Now all methods are valid. 

Sunita
________________________________________

**Pull request merged**
